# Generated by Django 4.1.3 on 2022-12-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_topic_remove_article_email_article_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
